// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "7e9cfc13-75a6-415e-9b77-a0f6816ac59c";

const char SSID[]               = "ChinaNet-602";    // Network SSID (name)
const char PASS[]               = "password";       // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "Ycj8Xj5ccZVJFBP9vcZQZY5@T";    // Secret device password


int water_level;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(water_level, READ, ON_CHANGE, NULL, 10);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
